/* tslint:disable */
/* eslint-disable */
/**
 * FakeRESTApi.Web V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface Activity
 */
export interface Activity {
  /**
   *
   * @type {number}
   * @memberof Activity
   */
  id?: number;
  /**
   *
   * @type {string}
   * @memberof Activity
   */
  title?: string | null;
  /**
   *
   * @type {Date}
   * @memberof Activity
   */
  dueDate?: Date;
  /**
   *
   * @type {boolean}
   * @memberof Activity
   */
  completed?: boolean;
}

/**
 * Check if a given object implements the Activity interface.
 */
export function instanceOfActivity(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function ActivityFromJSON(json: any): Activity {
  return ActivityFromJSONTyped(json, false);
}

export function ActivityFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): Activity {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, "id") ? undefined : json["id"],
    title: !exists(json, "title") ? undefined : json["title"],
    dueDate: !exists(json, "dueDate") ? undefined : new Date(json["dueDate"]),
    completed: !exists(json, "completed") ? undefined : json["completed"],
  };
}

export function ActivityToJSON(value?: Activity | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    title: value.title,
    dueDate:
      value.dueDate === undefined ? undefined : value.dueDate.toISOString(),
    completed: value.completed,
  };
}
