/* tslint:disable */
/* eslint-disable */
/**
 * FakeRESTApi.Web V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface Author
 */
export interface Author {
  /**
   *
   * @type {number}
   * @memberof Author
   */
  id?: number;
  /**
   *
   * @type {number}
   * @memberof Author
   */
  idBook?: number;
  /**
   *
   * @type {string}
   * @memberof Author
   */
  firstName?: string | null;
  /**
   *
   * @type {string}
   * @memberof Author
   */
  lastName?: string | null;
}

/**
 * Check if a given object implements the Author interface.
 */
export function instanceOfAuthor(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function AuthorFromJSON(json: any): Author {
  return AuthorFromJSONTyped(json, false);
}

export function AuthorFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): Author {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, "id") ? undefined : json["id"],
    idBook: !exists(json, "idBook") ? undefined : json["idBook"],
    firstName: !exists(json, "firstName") ? undefined : json["firstName"],
    lastName: !exists(json, "lastName") ? undefined : json["lastName"],
  };
}

export function AuthorToJSON(value?: Author | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    idBook: value.idBook,
    firstName: value.firstName,
    lastName: value.lastName,
  };
}
