/* tslint:disable */
/* eslint-disable */
/**
 * FakeRESTApi.Web V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface Book
 */
export interface Book {
  /**
   *
   * @type {number}
   * @memberof Book
   */
  id?: number;
  /**
   *
   * @type {string}
   * @memberof Book
   */
  title?: string | null;
  /**
   *
   * @type {string}
   * @memberof Book
   */
  description?: string | null;
  /**
   *
   * @type {number}
   * @memberof Book
   */
  pageCount?: number;
  /**
   *
   * @type {string}
   * @memberof Book
   */
  excerpt?: string | null;
  /**
   *
   * @type {Date}
   * @memberof Book
   */
  publishDate?: Date;
}

/**
 * Check if a given object implements the Book interface.
 */
export function instanceOfBook(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function BookFromJSON(json: any): Book {
  return BookFromJSONTyped(json, false);
}

export function BookFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): Book {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, "id") ? undefined : json["id"],
    title: !exists(json, "title") ? undefined : json["title"],
    description: !exists(json, "description") ? undefined : json["description"],
    pageCount: !exists(json, "pageCount") ? undefined : json["pageCount"],
    excerpt: !exists(json, "excerpt") ? undefined : json["excerpt"],
    publishDate: !exists(json, "publishDate")
      ? undefined
      : new Date(json["publishDate"]),
  };
}

export function BookToJSON(value?: Book | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    title: value.title,
    description: value.description,
    pageCount: value.pageCount,
    excerpt: value.excerpt,
    publishDate:
      value.publishDate === undefined
        ? undefined
        : value.publishDate.toISOString(),
  };
}
